# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35c06b01ff5141d4363cbf0cb39f25f67c09d7872f0bf447b8ed6c4b71e63c343c21240e4b1bc22241188640cc2af0e66bd0f18d7adff3251fdeeae70e19ab61

test:
  secret_key_base: 154a9dfb7b537d28c20ef664d30ac01fd0bdf49adb1ac652f6c74cee7cdac42fba1be49da738e0d33a56ac03030dbe6bba519018a1de9caf4f5ebef0e9f15fd3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
